module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    screens: {
      xs: '400px',
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px',
    },
    extend: {
      colors: {
        black: '#000700',
        black1: '#171725',
        blackBG: '#13131a',
        blackBG2: '#1c1c24',
        blackBG3: '#21212b',
        blackPadding: '#2c2c2c',
        natural: '#f4f4f4',
        natural2: '#f1f1f5',
        natural3: '#696974',
        natural4: '#fafafb',
        natural5: '#f5f5f8',
        natural6: '#92929D',
        naturalColor: '#44444f',
        naturalColor6: '#e2e2ea',
        naturalGray: '#CCCCCC',
        primary: '#529cf1',
        secondary1: '#add8e6',
        secondary2: '#d7d0ff',
        secondary3: '#fddd8c',
        secondary4: '#ffbbd7',
        white: '#ffffff',
      },
      fontFamily: {
        manrope: ['Manrope', 'sans-serif'],
        dmsans: ['DM Sans', 'sans-serif'],
      },
      fontWeight: {
        thin: 100,
        extralight: 200,
        light: 300,
        normal: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
        extrabold: 800,
        black: 900,
      },
    },
  },
  variants: {},
  plugins: [],
};
